[project]
name = "gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.3",
    "uvicorn[standard]>=0.30.0",
    "pydantic-settings>=2.3.4",
    "aiokafka>=0.12.0",
    "pydantic>=2.12.4",
]
